name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone buildroot
      uses: actions/checkout@v4
      with:
        repository: 'buildroot/buildroot'
        path: buildroot
    - name: Configure Buildroot
      run: |
        cd buildroot
        make BR2_EXTERNAL=. raspberrypi_2w_custom_defconfig
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
