name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Clone buildroot
      uses: actions/checkout@v4
      with:
        repository: 'buildroot/buildroot'
        path: buildroot
    - name: Restore cached buildroot host 
      id: brhost-restore
      uses: actions/cache/restore@v4
      with:
        path: |
            buildroot/output/host
            buildroot/output/build/host-*
        key: ${{ runner.os }}-brhost
        
    - name: Configure Buildroot
      run: |
        cd buildroot
        make BR2_EXTERNAL=.. raspberrypi_2w_custom_defconfig
    - name: make
      run: |
        cd buildroot
        make
