name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone buildroot
      uses: actions/checkout@v4
      with:
        repository: 'buildroot/buildroot'
      run: |
        cd <repository-name>
        ls -la
    - name: configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
